# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

language: scala

jdk:
  - oraclejdk8

scala:
   - 2.12.1

script:
   - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

notifications:
  slack: codeguru-il:ib2i4YtS2JSkO6mDzo4blcT6

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/test-reporter
  - sbt coveralls
  - sbt scalastyle
  - sbt coverageReport
  - sbt codacyCoverage

